// storybook/react/src/components/IBreadcrumb/dynamically-generated.tsx
import React from 'react';
import { IBreadcrumb, IBreadcrumbItem } from '@inkline/inkline/components';

export default (props: any) => {
    const items = [
        { title: 'Home', href: '/' },
        { title: 'Components', to: '/example' },
        { title: 'Breadcrumbs', active: true }
    ];

    return <>
        <IBreadcrumb {...props}>
            { items.map((item) =>
                <IBreadcrumbItem {...item} key={item.title}>
                    {item.title}
                </IBreadcrumbItem>)
            }
        </IBreadcrumb>
    </>;
};

// storybook/vue/src/components/IBreadcrumb/dynamically-generated.vue
<script lang="ts">
import { IBreadcrumb, IBreadcrumbItem } from '@inkline/inkline/components';
import { ref } from 'vue';

export default {
    components: {
        IBreadcrumb,
        IBreadcrumbItem
    },
    setup () {
        const items = ref([
            { title: 'Home', href: '/' },
            { title: 'Components', to: '/example' },
            { title: 'Breadcrumbs', active: true }
        ]);

        return { items };
    }
};
</script>
<template>
    <i-breadcrumb>
        <i-breadcrumb-item v-for="item in items" v-bind="item" :key="item.title">
            {{ item.title }}
        </i-breadcrumb-item>
    </i-breadcrumb>
</template>
