// src/components/IAlert/examples/react/dismissible.tsx
import React, { useState } from 'react';
import { IAlert } from '@inkline/inkline/components';

export default (props: any) => {
    const [visible, setVisible] = useState(true);

    return <>
        <IAlert dismissible modelValue={visible} onUpdateModelValue={setVisible} {...props}>
            <p>Whoa! Nicely done.</p>
        </IAlert>
    </>;
};

// storybook/vue3/src/components/IAlert/dismissible.vue
<script lang="ts">
import { IAlert } from '@inkline/inkline/components';

export default {
    components: {
        IAlert
    },
    data () {
        return {
            visible: true
        };
    }
};
</script>
<template>
    <i-alert v-model="visible" dismissible v-bind="$attrs">
        <p>Whoa! Nicely done. {{ visible }}</p>
    </i-alert>
</template>
