// src/components/IBadge/examples/react/heading.tsx
import React from 'react';
import { IBadge } from '@inkline/inkline/components';

export default () => <>
    <h1>Heading 1 <IBadge color="primary">New</IBadge></h1>

    <h2>Heading 2 <IBadge color="primary">New</IBadge></h2>

    <h3>Heading 3 <IBadge color="primary">New</IBadge></h3>

    <h4>Heading 4 <IBadge color="primary">New</IBadge></h4>

    <h5>Heading 5 <IBadge color="primary">New</IBadge></h5>

    <h6>Heading 6 <IBadge color="primary">New</IBadge></h6>
</>;

// packages/components/badge/src/examples/heading.vue
<template>
    <h1>Heading 1 <Badge color="primary">New</Badge></h1>

    <h2>Heading 2 <Badge color="primary">New</Badge></h2>

    <h3>Heading 3 <Badge color="primary">New</Badge></h3>

    <h4>Heading 4 <Badge color="primary">New</Badge></h4>

    <h5>Heading 5 <Badge color="primary">New</Badge></h5>

    <h6>Heading 6 <Badge color="primary">New</Badge></h6>
</template>
