// storybook/react/src/components/IBreadcrumb/dynamically-generated.tsx
import React from 'react';
import { IBreadcrumb, IBreadcrumbItem } from '@inkline/inkline/components';

export default (props: any) => {
    const items = [
        { title: 'Home', href: '/' },
        { title: 'Components', to: '/example' },
        { title: 'Breadcrumbs', active: true }
    ];

    return <>
        <IBreadcrumb {...props}>
            { items.map((item) =>
                <IBreadcrumbItem {...item} key={item.title}>
                    {item.title}
                </IBreadcrumbItem>)
            }
        </IBreadcrumb>
    </>;
};

// src/components/IBreadcrumb/examples/dynamically-generated.vue
<script lang="ts" setup>
const items = [
    { title: 'Home', href: '/' },
    { title: 'Components', to: 'components' },
    { title: 'Breadcrumbs', active: true }
];
</script>

<template>
    <IBreadcrumb>
        <IBreadcrumbItem v-for="item in items" v-bind="item" :key="item.title">
            {{ item.title }}
        </IBreadcrumbItem>
    </IBreadcrumb>
</template>
