// src/components/IBreadcrumb/examples/routing.vue
<template>
    <i-breadcrumb>
        <i-breadcrumb-item href="/">Home</i-breadcrumb-item>
        <i-breadcrumb-item :to="{ name: 'docs' }">Library</i-breadcrumb-item>
        <i-breadcrumb-item>Example</i-breadcrumb-item>
        <i-breadcrumb-item active>Data</i-breadcrumb-item>
    </i-breadcrumb>
</template>

// storybook/react/src/components/IBreadcrumb/routing.tsx
import React from 'react';
import { IBreadcrumb, IBreadcrumbItem } from '@inkline/inkline/components';

export default (props: any) => <>
    <IBreadcrumb {...props}>
        <IBreadcrumbItem href="/">Home</IBreadcrumbItem>
        <IBreadcrumbItem to="/example">Library</IBreadcrumbItem>
        <IBreadcrumbItem>Example</IBreadcrumbItem>
        <IBreadcrumbItem active>Data</IBreadcrumbItem>
    </IBreadcrumb>
</>;
