// packages/vue/src/components/IAlert/examples/content.vue
<template>
    <IAlert>
        <template #icon>
            <IIcon name="ink-info" size="lg" />
        </template>
        <strong>Alert Title</strong>
        <p>
            Some quick example text and an <a href="https://inkline.io">example link</a> to build on
            the alert and make up the bulk of the alert's content.
        </p>
    </IAlert>
</template>
<script setup lang="ts"></script>

// storybook/react/src/components/IAlert/content.tsx
import React from 'react';
import { IAlert, IIcon } from '@inkline/inkline/components';

export default (props: any) => <>
    <IAlert {...props}>
        <IAlert.Icon>
            <IIcon name="ink-info" size="lg" />
        </IAlert.Icon>
        <h4 className="_margin-bottom:0">Alert Title</h4>
        <p className="_margin-top:0">
            Some quick example text to build on the alert and make up the bulk of the alert's content.
        </p>
    </IAlert>
</>;
