// storybook/react/src/components/IAlert/content.tsx
import React from 'react';
import { IAlert, IIcon } from '@inkline/inkline/components';

export default (props: any) => <>
    <IAlert {...props}>
        <IAlert.Icon>
            <IIcon name="ink-info" size="lg" />
        </IAlert.Icon>
        <h4 className="_margin-bottom:0">Alert Title</h4>
        <p className="_margin-top:0">
            Some quick example text to build on the alert and make up the bulk of the alert's content.
        </p>
    </IAlert>
</>;

// src/components/IAlert/examples/content.vue
<template>
    <IAlert>
        <template #icon>
            <IIcon name="ink-info" size="lg" />
        </template>
        <h4 class="_margin-bottom:0">Alert Title</h4>
        <p class="_margin-top:0">
            Some quick example text to build on the alert and make up the bulk of the alert's
            content.
        </p>
    </IAlert>
</template>
